package com.black.tea.cxf.weather;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-12T11:12:35.408+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "WeatherInterfaceService",
                  wsdlLocation = "http://127.0.0.1:1997/weather?WSDL",
                  targetNamespace = "http://server.cxf.tea.black.com/")
public class WeatherInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.cxf.tea.black.com/", "WeatherInterfaceService");
    public final static QName WeatherInterfacePort = new QName("http://server.cxf.tea.black.com/", "WeatherInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:1997/weather?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WeatherInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:1997/weather?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WeatherInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WeatherInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WeatherInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WeatherInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WeatherInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WeatherInterface
     */
    @WebEndpoint(name = "WeatherInterfacePort")
    public WeatherInterface getWeatherInterfacePort() {
        return super.getPort(WeatherInterfacePort, WeatherInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherInterface
     */
    @WebEndpoint(name = "WeatherInterfacePort")
    public WeatherInterface getWeatherInterfacePort(WebServiceFeature... features) {
        return super.getPort(WeatherInterfacePort, WeatherInterface.class, features);
    }

}
